
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/cmake-4.2.3-windows-x86_64/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
...
